### ISSUE TITLE
Multi-Byte length handling is wrong

### ISSUE THREAD

**Issue by zecke** [mitshell/card#1]
The condition:  

   # Length coded with more than 1 byte
    if bytelist[i+1] > 0x50:

is wrong. The extended length is indicated in bit 0x80 and the rest then is either the amount of octets needed to describe the length or uses the indefinite length. The issue can be seen by using USIM with the sysmoUSIM-SJS1 card.

**Comment by mitshell** [comment]
Commit 815cbf6 should correct this, but only for definite length
