### ISSUE TITLE
5GS EF5GS3GPPLOCI Unable to read it

### ISSUE THREAD

**Issue by ljubo2015** [mitshell/card#10]
I have tried to read following information from SIM card: 
![image](https://user-images.githubusercontent.com/15197215/136652930-1d2ca2cd-3f3f-4a12-816f-a412ea6fb8b8.png)

To be more precise reading 4F01 but it always returns me empty values? Any advise how to read this field and if its supported by card tool at all?

**Comment by mitshell** [comment]
Actually, `card` does not support any specific file structure (or just the IMSI and ICCID), it supports reading the different types of EF, and providing the bytes stored in there. If you get an empty sequence of bytes, or a sequence of 0xFF bytes, this means your SIM has the file available, but it has not been set by your operator.

If you feel you are doing something wrong, please post the list of command you sent to and results you got from the card, stored under the `.coms` attribute of your USIM instance.
