### ISSUE TITLE
verify/change PIN on a VISA

### ISSUE THREAD

**Issue by iddq** [mitshell/card#3]
Hello,

Can you please help me how could I verify/change PIN on a VISA?

Thanks

> Outgoing APDU (13 bytes):
> 00 20 00 01 08 31 31 31 31 31 31 31 31 . ...11111111
> 
> Incoming APDU (2 bytes):
> 6D 00 m.
> 
> iso7816.c:121:iso7816_check_sw: Instruction code not supported or invalid
> 
> Unable to verify PIN code: Unsupported INS byte in APDU

**Comment by mitshell** [comment]
Hello,
I have no clue about VISA card and how it is working. It may be described in the EMV specification, be even that I am not sure of... In case you find out how to do it, do not hesitate to send back some information, or even better some code to support it.
Thanks
