### ISSUE TITLE
Port the code to Python3

### ISSUE THREAD

**Issue by LudovicRousseau** [mitshell/card#7]
I used `2to3` to port the files to Python3.
That would generate a big PR. You may want to use `2to3` on your side instead to not have to review a big patch.

I was able to make the code work fine on both Python 2 and Python 3. But maybe you want to drop Python 2 support to ease the maintenance.

If you need more help just tell me.

**Comment by mitshell** [comment]
Thanks for the proposal.
I would prefer to keep the support for both Python version 2 and 3. I need to check precisely what part of the library fails with python3. I am not a big fan of 2to3 but I will give it a shot to see the result.

**Comment by LudovicRousseau** [comment]
2to3 does not remove the support of Python2.

For example you can have a look at my python3 branch in https://github.com/LudovicRousseau/osmo-sim-auth/tree/python3
This code also works with Python2.

**Comment by LudovicRousseau** [comment]
Any progress on this issue?
Do you want me to propose a PR instead?

**Comment by mitshell** [comment]
I have just tested the library with the SIM, USIM and GP classes (but not every methods), without entering any issues on Python 3.8.5 (on Ubuntu 20.04). Did you had any issue with running the current version of the library on Python 3 on your side ?
The fact is that you have been porting to Python3 a version of `card` dating from 2011, which may also have evolved independently from my version.

**Comment by LudovicRousseau** [comment]
Oops. Sorry.
I could not imagine that https://github.com/osmocom/osmo-sim-auth was using a very old copy of your code.

My problem is tracked (downstream) at https://gerrit.osmocom.org/c/osmo-sim-auth/+/20903
