### ISSUE TITLE
Use markdown for README?

### ISSUE THREAD

**Issue by LudovicRousseau** [mitshell/card#8]
I suggest to rename `README.txt` in `README.md` to get a nicer rendering of the file.
You will have to modify the file a bit to follow the markdown syntax but it is easy.

See https://guides.github.com/features/mastering-markdown/

**Comment by mitshell** [comment]
I know markdown, thanks.
I need however to find the time to rewrite a nice and more complete README for the library. Any help appreciated here :)

**Comment by LudovicRousseau** [comment]
I also often have a lack of free time :-)
No urgency. And thanks for your feedback.

**Comment by mitshell** [comment]
Finally found the time, as you triggered me reworking on the library !
